//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CLivroAutor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CLivroAutor.ICLivroAutor")]
    public interface ICLivroAutor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivroAutor/InserirNpraN", ReplyAction="http://tempuri.org/ICLivroAutor/InserirNpraNResponse")]
        void InserirNpraN(Model.LIVRO oLivro, int Autor1, int Autor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivroAutor/InserirNpraN", ReplyAction="http://tempuri.org/ICLivroAutor/InserirNpraNResponse")]
        System.Threading.Tasks.Task InserirNpraNAsync(Model.LIVRO oLivro, int Autor1, int Autor2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICLivroAutorChannel : View.CLivroAutor.ICLivroAutor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CLivroAutorClient : System.ServiceModel.ClientBase<View.CLivroAutor.ICLivroAutor>, View.CLivroAutor.ICLivroAutor {
        
        public CLivroAutorClient() {
        }
        
        public CLivroAutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CLivroAutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLivroAutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLivroAutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InserirNpraN(Model.LIVRO oLivro, int Autor1, int Autor2) {
            base.Channel.InserirNpraN(oLivro, Autor1, Autor2);
        }
        
        public System.Threading.Tasks.Task InserirNpraNAsync(Model.LIVRO oLivro, int Autor1, int Autor2) {
            return base.Channel.InserirNpraNAsync(oLivro, Autor1, Autor2);
        }
    }
}
