//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO
    {
        public ALUNO()
        {
            this.EMPRESTIMO = new HashSet<EMPRESTIMO>();
        }
    
        public int ID_ALUNO { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string CPF { get; set; }
        public System.DateTime NASC { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string PAIS { get; set; }
        public string TEL_RES { get; set; }
        public string TEL_CEL { get; set; }
        public int ID_RESERVA { get; set; }
        public string EMAIL { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual ICollection<EMPRESTIMO> EMPRESTIMO { get; set; }
    }
}
