//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESTIMO
    {
        public int ID_EMPRESTIMO { get; set; }
        public System.DateTime DATA_EMP { get; set; }
        public System.DateTime DATA_DEVOL { get; set; }
        public int ID_ALUNO { get; set; }
        public int ID_LIVRO { get; set; }
        public string SITUACAO { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
        public virtual LIVRO LIVRO { get; set; }
    }
}
