//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERO
    {
        public GENERO()
        {
            this.LIVRO = new HashSet<LIVRO>();
        }
    
        public int ID_GENERO { get; set; }
        public string DESCRICAO { get; set; }
        public string ANDAR { get; set; }
        public string CORREDOR { get; set; }
        public string PRETELEIRA { get; set; }
    
        public virtual ICollection<LIVRO> LIVRO { get; set; }
    }
}
