//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.LIVRO = new HashSet<LIVRO>();
        }
    
        public int ID_RESERVA { get; set; }
        public System.DateTime DATA_RES { get; set; }
    
        public virtual ICollection<LIVRO> LIVRO { get; set; }
    }
}
