//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CRelatorioEditora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRelatorioEditora.ICRelatorioEditora")]
    public interface ICRelatorioEditora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEditora/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioEditora/GerarRelatorioIDResponse")]
        Model.EDITORA[] GerarRelatorioID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEditora/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioEditora/GerarRelatorioIDResponse")]
        System.Threading.Tasks.Task<Model.EDITORA[]> GerarRelatorioIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEditora/GerarRelatorioNome", ReplyAction="http://tempuri.org/ICRelatorioEditora/GerarRelatorioNomeResponse")]
        Model.EDITORA[] GerarRelatorioNome();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEditora/GerarRelatorioNome", ReplyAction="http://tempuri.org/ICRelatorioEditora/GerarRelatorioNomeResponse")]
        System.Threading.Tasks.Task<Model.EDITORA[]> GerarRelatorioNomeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRelatorioEditoraChannel : View.CRelatorioEditora.ICRelatorioEditora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRelatorioEditoraClient : System.ServiceModel.ClientBase<View.CRelatorioEditora.ICRelatorioEditora>, View.CRelatorioEditora.ICRelatorioEditora {
        
        public CRelatorioEditoraClient() {
        }
        
        public CRelatorioEditoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRelatorioEditoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioEditoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioEditoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.EDITORA[] GerarRelatorioID() {
            return base.Channel.GerarRelatorioID();
        }
        
        public System.Threading.Tasks.Task<Model.EDITORA[]> GerarRelatorioIDAsync() {
            return base.Channel.GerarRelatorioIDAsync();
        }
        
        public Model.EDITORA[] GerarRelatorioNome() {
            return base.Channel.GerarRelatorioNome();
        }
        
        public System.Threading.Tasks.Task<Model.EDITORA[]> GerarRelatorioNomeAsync() {
            return base.Channel.GerarRelatorioNomeAsync();
        }
    }
}
