//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CRelatorioReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRelatorioReserva.ICRelatorioReserva")]
    public interface ICRelatorioReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioReserva/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioReserva/GerarRelatorioIDResponse")]
        Model.RESERVA[] GerarRelatorioID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioReserva/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioReserva/GerarRelatorioIDResponse")]
        System.Threading.Tasks.Task<Model.RESERVA[]> GerarRelatorioIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioReserva/GerarRelatorioAluno", ReplyAction="http://tempuri.org/ICRelatorioReserva/GerarRelatorioAlunoResponse")]
        Model.RESERVA[] GerarRelatorioAluno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioReserva/GerarRelatorioAluno", ReplyAction="http://tempuri.org/ICRelatorioReserva/GerarRelatorioAlunoResponse")]
        System.Threading.Tasks.Task<Model.RESERVA[]> GerarRelatorioAlunoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRelatorioReservaChannel : View.CRelatorioReserva.ICRelatorioReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRelatorioReservaClient : System.ServiceModel.ClientBase<View.CRelatorioReserva.ICRelatorioReserva>, View.CRelatorioReserva.ICRelatorioReserva {
        
        public CRelatorioReservaClient() {
        }
        
        public CRelatorioReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRelatorioReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.RESERVA[] GerarRelatorioID() {
            return base.Channel.GerarRelatorioID();
        }
        
        public System.Threading.Tasks.Task<Model.RESERVA[]> GerarRelatorioIDAsync() {
            return base.Channel.GerarRelatorioIDAsync();
        }
        
        public Model.RESERVA[] GerarRelatorioAluno() {
            return base.Channel.GerarRelatorioAluno();
        }
        
        public System.Threading.Tasks.Task<Model.RESERVA[]> GerarRelatorioAlunoAsync() {
            return base.Channel.GerarRelatorioAlunoAsync();
        }
    }
}
