//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CEmprestimo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEmprestimo.ICEmprestimo")]
    public interface ICEmprestimo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Emprestar", ReplyAction="http://tempuri.org/ICEmprestimo/EmprestarResponse")]
        void Emprestar(int idAluno, int idLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Emprestar", ReplyAction="http://tempuri.org/ICEmprestimo/EmprestarResponse")]
        System.Threading.Tasks.Task EmprestarAsync(int idAluno, int idLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/listaTodosEmprestimosAluno", ReplyAction="http://tempuri.org/ICEmprestimo/listaTodosEmprestimosAlunoResponse")]
        Model.EMPRESTIMO[] listaTodosEmprestimosAluno(int idAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/listaTodosEmprestimosAluno", ReplyAction="http://tempuri.org/ICEmprestimo/listaTodosEmprestimosAlunoResponse")]
        System.Threading.Tasks.Task<Model.EMPRESTIMO[]> listaTodosEmprestimosAlunoAsync(int idAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/RenovarEmprestimo", ReplyAction="http://tempuri.org/ICEmprestimo/RenovarEmprestimoResponse")]
        void RenovarEmprestimo(int idEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/RenovarEmprestimo", ReplyAction="http://tempuri.org/ICEmprestimo/RenovarEmprestimoResponse")]
        System.Threading.Tasks.Task RenovarEmprestimoAsync(int idEmp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICEmprestimoChannel : View.CEmprestimo.ICEmprestimo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CEmprestimoClient : System.ServiceModel.ClientBase<View.CEmprestimo.ICEmprestimo>, View.CEmprestimo.ICEmprestimo {
        
        public CEmprestimoClient() {
        }
        
        public CEmprestimoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CEmprestimoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CEmprestimoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CEmprestimoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Emprestar(int idAluno, int idLivro) {
            base.Channel.Emprestar(idAluno, idLivro);
        }
        
        public System.Threading.Tasks.Task EmprestarAsync(int idAluno, int idLivro) {
            return base.Channel.EmprestarAsync(idAluno, idLivro);
        }
        
        public Model.EMPRESTIMO[] listaTodosEmprestimosAluno(int idAluno) {
            return base.Channel.listaTodosEmprestimosAluno(idAluno);
        }
        
        public System.Threading.Tasks.Task<Model.EMPRESTIMO[]> listaTodosEmprestimosAlunoAsync(int idAluno) {
            return base.Channel.listaTodosEmprestimosAlunoAsync(idAluno);
        }
        
        public void RenovarEmprestimo(int idEmp) {
            base.Channel.RenovarEmprestimo(idEmp);
        }
        
        public System.Threading.Tasks.Task RenovarEmprestimoAsync(int idEmp) {
            return base.Channel.RenovarEmprestimoAsync(idEmp);
        }
    }
}
