//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CTeste {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CTeste.ICTeste")]
    public interface ICTeste {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTeste/ListaAlunos", ReplyAction="http://tempuri.org/ICTeste/ListaAlunosResponse")]
        Model.ALUNO[] ListaAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTeste/ListaAlunos", ReplyAction="http://tempuri.org/ICTeste/ListaAlunosResponse")]
        System.Threading.Tasks.Task<Model.ALUNO[]> ListaAlunosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTesteChannel : View.CTeste.ICTeste, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTesteClient : System.ServiceModel.ClientBase<View.CTeste.ICTeste>, View.CTeste.ICTeste {
        
        public CTesteClient() {
        }
        
        public CTesteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTesteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTesteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTesteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.ALUNO[] ListaAlunos() {
            return base.Channel.ListaAlunos();
        }
        
        public System.Threading.Tasks.Task<Model.ALUNO[]> ListaAlunosAsync() {
            return base.Channel.ListaAlunosAsync();
        }
    }
}
