//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CRelatorioEmprestimo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRelatorioEmprestimo.ICRelatorioEmprestimo")]
    public interface ICRelatorioEmprestimo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioIDResponse")]
        Model.EMPRESTIMO[] GerarRelatorioID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioIDResponse")]
        System.Threading.Tasks.Task<Model.EMPRESTIMO[]> GerarRelatorioIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioAluno", ReplyAction="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioAlunoResponse")]
        Model.EMPRESTIMO[] GerarRelatorioAluno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioAluno", ReplyAction="http://tempuri.org/ICRelatorioEmprestimo/GerarRelatorioAlunoResponse")]
        System.Threading.Tasks.Task<Model.EMPRESTIMO[]> GerarRelatorioAlunoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRelatorioEmprestimoChannel : View.CRelatorioEmprestimo.ICRelatorioEmprestimo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRelatorioEmprestimoClient : System.ServiceModel.ClientBase<View.CRelatorioEmprestimo.ICRelatorioEmprestimo>, View.CRelatorioEmprestimo.ICRelatorioEmprestimo {
        
        public CRelatorioEmprestimoClient() {
        }
        
        public CRelatorioEmprestimoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRelatorioEmprestimoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioEmprestimoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioEmprestimoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.EMPRESTIMO[] GerarRelatorioID() {
            return base.Channel.GerarRelatorioID();
        }
        
        public System.Threading.Tasks.Task<Model.EMPRESTIMO[]> GerarRelatorioIDAsync() {
            return base.Channel.GerarRelatorioIDAsync();
        }
        
        public Model.EMPRESTIMO[] GerarRelatorioAluno() {
            return base.Channel.GerarRelatorioAluno();
        }
        
        public System.Threading.Tasks.Task<Model.EMPRESTIMO[]> GerarRelatorioAlunoAsync() {
            return base.Channel.GerarRelatorioAlunoAsync();
        }
    }
}
