//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CRelatorioGenero {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRelatorioGenero.ICRelatorioGenero")]
    public interface ICRelatorioGenero {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioGenero/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioGenero/GerarRelatorioIDResponse")]
        Model.GENERO[] GerarRelatorioID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioGenero/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioGenero/GerarRelatorioIDResponse")]
        System.Threading.Tasks.Task<Model.GENERO[]> GerarRelatorioIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioGenero/GerarRelatorioDescricao", ReplyAction="http://tempuri.org/ICRelatorioGenero/GerarRelatorioDescricaoResponse")]
        Model.GENERO[] GerarRelatorioDescricao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioGenero/GerarRelatorioDescricao", ReplyAction="http://tempuri.org/ICRelatorioGenero/GerarRelatorioDescricaoResponse")]
        System.Threading.Tasks.Task<Model.GENERO[]> GerarRelatorioDescricaoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRelatorioGeneroChannel : View.CRelatorioGenero.ICRelatorioGenero, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRelatorioGeneroClient : System.ServiceModel.ClientBase<View.CRelatorioGenero.ICRelatorioGenero>, View.CRelatorioGenero.ICRelatorioGenero {
        
        public CRelatorioGeneroClient() {
        }
        
        public CRelatorioGeneroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRelatorioGeneroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioGeneroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioGeneroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.GENERO[] GerarRelatorioID() {
            return base.Channel.GerarRelatorioID();
        }
        
        public System.Threading.Tasks.Task<Model.GENERO[]> GerarRelatorioIDAsync() {
            return base.Channel.GerarRelatorioIDAsync();
        }
        
        public Model.GENERO[] GerarRelatorioDescricao() {
            return base.Channel.GerarRelatorioDescricao();
        }
        
        public System.Threading.Tasks.Task<Model.GENERO[]> GerarRelatorioDescricaoAsync() {
            return base.Channel.GerarRelatorioDescricaoAsync();
        }
    }
}
