//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CRelatorioAutor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRelatorioAutor.ICRelatorioAutor")]
    public interface ICRelatorioAutor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioAutor/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioAutor/GerarRelatorioIDResponse")]
        Model.AUTOR[] GerarRelatorioID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioAutor/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioAutor/GerarRelatorioIDResponse")]
        System.Threading.Tasks.Task<Model.AUTOR[]> GerarRelatorioIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioAutor/GerarRelatorioNome", ReplyAction="http://tempuri.org/ICRelatorioAutor/GerarRelatorioNomeResponse")]
        Model.AUTOR[] GerarRelatorioNome();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioAutor/GerarRelatorioNome", ReplyAction="http://tempuri.org/ICRelatorioAutor/GerarRelatorioNomeResponse")]
        System.Threading.Tasks.Task<Model.AUTOR[]> GerarRelatorioNomeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRelatorioAutorChannel : View.CRelatorioAutor.ICRelatorioAutor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRelatorioAutorClient : System.ServiceModel.ClientBase<View.CRelatorioAutor.ICRelatorioAutor>, View.CRelatorioAutor.ICRelatorioAutor {
        
        public CRelatorioAutorClient() {
        }
        
        public CRelatorioAutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRelatorioAutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioAutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioAutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.AUTOR[] GerarRelatorioID() {
            return base.Channel.GerarRelatorioID();
        }
        
        public System.Threading.Tasks.Task<Model.AUTOR[]> GerarRelatorioIDAsync() {
            return base.Channel.GerarRelatorioIDAsync();
        }
        
        public Model.AUTOR[] GerarRelatorioNome() {
            return base.Channel.GerarRelatorioNome();
        }
        
        public System.Threading.Tasks.Task<Model.AUTOR[]> GerarRelatorioNomeAsync() {
            return base.Channel.GerarRelatorioNomeAsync();
        }
    }
}
