//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CReserva.ICReserva")]
    public interface ICReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICReserva/Reservar", ReplyAction="http://tempuri.org/ICReserva/ReservarResponse")]
        void Reservar(int idAluno, int idLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICReserva/Reservar", ReplyAction="http://tempuri.org/ICReserva/ReservarResponse")]
        System.Threading.Tasks.Task ReservarAsync(int idAluno, int idLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICReserva/listaTodasReservasAluno", ReplyAction="http://tempuri.org/ICReserva/listaTodasReservasAlunoResponse")]
        Model.RESERVA[] listaTodasReservasAluno(int idAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICReserva/listaTodasReservasAluno", ReplyAction="http://tempuri.org/ICReserva/listaTodasReservasAlunoResponse")]
        System.Threading.Tasks.Task<Model.RESERVA[]> listaTodasReservasAlunoAsync(int idAluno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICReservaChannel : View.CReserva.ICReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CReservaClient : System.ServiceModel.ClientBase<View.CReserva.ICReserva>, View.CReserva.ICReserva {
        
        public CReservaClient() {
        }
        
        public CReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Reservar(int idAluno, int idLivro) {
            base.Channel.Reservar(idAluno, idLivro);
        }
        
        public System.Threading.Tasks.Task ReservarAsync(int idAluno, int idLivro) {
            return base.Channel.ReservarAsync(idAluno, idLivro);
        }
        
        public Model.RESERVA[] listaTodasReservasAluno(int idAluno) {
            return base.Channel.listaTodasReservasAluno(idAluno);
        }
        
        public System.Threading.Tasks.Task<Model.RESERVA[]> listaTodasReservasAlunoAsync(int idAluno) {
            return base.Channel.listaTodasReservasAlunoAsync(idAluno);
        }
    }
}
