//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.CRelatorioLivro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRelatorioLivro.ICRelatorioLivro")]
    public interface ICRelatorioLivro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioLivro/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioLivro/GerarRelatorioIDResponse")]
        Model.LIVRO[] GerarRelatorioID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioLivro/GerarRelatorioID", ReplyAction="http://tempuri.org/ICRelatorioLivro/GerarRelatorioIDResponse")]
        System.Threading.Tasks.Task<Model.LIVRO[]> GerarRelatorioIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioLivro/GerarRelatorioTitulo", ReplyAction="http://tempuri.org/ICRelatorioLivro/GerarRelatorioTituloResponse")]
        Model.LIVRO[] GerarRelatorioTitulo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRelatorioLivro/GerarRelatorioTitulo", ReplyAction="http://tempuri.org/ICRelatorioLivro/GerarRelatorioTituloResponse")]
        System.Threading.Tasks.Task<Model.LIVRO[]> GerarRelatorioTituloAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRelatorioLivroChannel : View.CRelatorioLivro.ICRelatorioLivro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRelatorioLivroClient : System.ServiceModel.ClientBase<View.CRelatorioLivro.ICRelatorioLivro>, View.CRelatorioLivro.ICRelatorioLivro {
        
        public CRelatorioLivroClient() {
        }
        
        public CRelatorioLivroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRelatorioLivroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioLivroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRelatorioLivroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.LIVRO[] GerarRelatorioID() {
            return base.Channel.GerarRelatorioID();
        }
        
        public System.Threading.Tasks.Task<Model.LIVRO[]> GerarRelatorioIDAsync() {
            return base.Channel.GerarRelatorioIDAsync();
        }
        
        public Model.LIVRO[] GerarRelatorioTitulo() {
            return base.Channel.GerarRelatorioTitulo();
        }
        
        public System.Threading.Tasks.Task<Model.LIVRO[]> GerarRelatorioTituloAsync() {
            return base.Channel.GerarRelatorioTituloAsync();
        }
    }
}
